name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
          cache-dependency-path: |
            yarn.lock
            packages/*/yarn.lock

      - name: Install dependencies
        run: yarn install --ignore-engines --immutable

      - name: Build all packages
        run: yarn workspaces foreach -v run build

      - name: Run tests (if any)
        run: yarn workspaces foreach -v run test || echo "No tests found"
