name: npm run CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x, 22.x] # remove o 18, já que alguns pacotes não suportam

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      # 🧩 ATIVA Yarn Berry ANTES de instalar as dependências
      - name: Enable Yarn Berry
        run: yarn set version berry

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build all workspaces
        run: yarn workspaces foreach --all --topological -v run build
